name = "flareact-ts"
type = "webpack"
account_id = "24"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"
vars = { GRAPHQL_API = "https://api.spacex.land/graphql/" }

[site]
bucket = "out"
entry-point = "./"
